In [3]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random

import cv2
from keras.models import load_model
import numpy as np


In [4]:
from keras.preprocessing import image
model = load_model('C:/Users/surek/Downloads/face recognition/facefeatures_new_model.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('C:/Users/surek/Downloads/face recognition/haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

<>:14: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:14: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\surek\AppData\Local\Temp\ipykernel_15864\4135753420.py:14: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [ ]:
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.7):
            name='Shreya'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        
            
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

1/1 [==============================] - 2s 2s/step
[[1. 0.]]
1/1 [==============================] - 0s 298ms/step
[[1. 0.]]
1/1 [==============================] - 0s 289ms/step
[[1.0000000e+00 4.5206914e-34]]
1/1 [==============================] - 0s 167ms/step
[[1.0000000e+00 2.3021893e-11]]
1/1 [==============================] - 0s 170ms/step
[[1.0000000e+00 1.2680494e-12]]
1/1 [==============================] - 0s 155ms/step
[[1. 0.]]
1/1 [==============================] - 0s 196ms/step
[[1. 0.]]
1/1 [==============================] - 0s 167ms/step
[[1. 0.]]
1/1 [==============================] - 0s 161ms/step
[[1.0000000e+00 8.4026265e-29]]
1/1 [==============================] - 0s 159ms/step
[[1.0000000e+00 3.4969194e-34]]
1/1 [==============================] - 0s 167ms/step
[[1.0000000e+00 2.1527093e-23]]
1/1 [==============================] - 0s 190ms/step
[[1.000000e+00 7.534267e-32]]
1/1 [==============================] - 0s 155ms/step
[[1. 0.]]
1/1 [===========================